"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-78p9350z)%^n7gjul4h2y$$_p84tb&9*g7nrqw@wyro7-@8s$o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Configurar ALLOWED_HOSTS a partir de variável de ambiente
# Aceita formato: "host1,host2,host3" ou "*" para aceitar todos
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else ['localhost', '127.0.0.1']
if '*' in ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'django_redis',
    'django_celery_beat',  # ✅ NOVO: Celery Beat para tasks agendadas
    # Local apps
    'transcription',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Whisper Configuration
WHISPER_MODEL = os.getenv('WHISPER_MODEL', 'medium')
WHISPER_LANGUAGE = os.getenv('WHISPER_LANGUAGE', 'pt')  # Português como padrão
WHISPER_LANGUAGE_NAME = 'pt-BR'  # Português Brasileiro
MAX_AUDIO_SIZE_MB = int(os.getenv('MAX_AUDIO_SIZE_MB', 500))  # 500 MB padrão
TEMP_AUDIO_DIR = os.getenv('TEMP_AUDIO_DIR', '/tmp/daredevil')
ENABLE_CACHE = os.getenv('ENABLE_CACHE', 'true').lower() == 'true'

# Cache Configuration
CACHE_SIZE = int(os.getenv('CACHE_SIZE', 100))  # Número máximo de itens no cache
CACHE_TTL_SECONDS = int(os.getenv('CACHE_TTL_SECONDS', 3600))  # 1 hora padrão
ENABLE_DISK_CACHE = os.getenv('ENABLE_DISK_CACHE', 'false').lower() == 'true'

# GPU Configuration
GPU_MEMORY_THRESHOLD = float(os.getenv('GPU_MEMORY_THRESHOLD', 0.9))  # 90% uso antes de fallback CPU
# ✅ NOVO: Distribuição de GPUs entre workers
NUM_GPUS = int(os.getenv('NUM_GPUS', 2))  # Número de GPUs disponíveis
CUDA_VISIBLE_DEVICES = os.getenv('CUDA_VISIBLE_DEVICES', '0,1')  # GPUs visíveis

# Redis Configuration
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# ========== REMOTE AUDIO CONVERTER CONFIGURATION ==========
# ✨ NOVO: Integração com serviço remoto de conversão de áudio
# Máquina remota com mais poder de processamento para conversão de áudio/vídeo
# 🚀 ATIVO: Use o IP real da máquina host (ex: 192.168.1.29 ou 192.168.1.33)
REMOTE_CONVERTER_URL = os.getenv(
    'REMOTE_CONVERTER_URL',
    'http://192.168.1.33:8591'  # ✅ Use o IP real da sua máquina
)
REMOTE_CONVERTER_ENABLED = os.getenv('REMOTE_CONVERTER_ENABLED', 'true').lower() == 'true'
REMOTE_CONVERTER_TIMEOUT = int(os.getenv('REMOTE_CONVERTER_TIMEOUT', '600'))  # 10 minutos
REMOTE_CONVERTER_MAX_RETRIES = int(os.getenv('REMOTE_CONVERTER_MAX_RETRIES', '2'))

# Celery Configuration
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', REDIS_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutos (aviso antes do hard limit)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # Processar uma tarefa por vez
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10  # Reiniciar worker após 10 tarefas (limpar memória)

# ========== PROTEÇÕES CONTRA TRAVAMENTO ==========
# ✅ NOVO: Celery Beat Schedule - Tarefas agendadas de proteção

CELERY_BEAT_SCHEDULE = {
    'cleanup-temp-files': {
        'task': 'transcription.cleanup_temp_files_task',
        'schedule': 30 * 60,  # A cada 30 minutos
        'options': {'time_limit': 600, 'soft_time_limit': 500}
    },
    'monitor-memory': {
        'task': 'transcription.monitor_memory_task',
        'schedule': 5 * 60,  # A cada 5 minutos
        'options': {'time_limit': 300, 'soft_time_limit': 250}
    },
    'unload-gpu-model': {
        'task': 'transcription.unload_gpu_model_task',
        'schedule': 60 * 60,  # A cada 1 hora
        'options': {'time_limit': 60, 'soft_time_limit': 45}
    },
}

# ✅ NOVO: Memory Protection Settings - Limites de segurança
MEMORY_CRITICAL_THRESHOLD_PERCENT = int(os.getenv('MEMORY_CRITICAL_THRESHOLD_PERCENT', 90))  # RAM > 90% = crítico
MEMORY_WARNING_THRESHOLD_PERCENT = int(os.getenv('MEMORY_WARNING_THRESHOLD_PERCENT', 75))  # RAM > 75% = aviso
DISK_CRITICAL_THRESHOLD_PERCENT = int(os.getenv('DISK_CRITICAL_THRESHOLD_PERCENT', 90))  # Disco > 90% = crítico
TEMP_DIR_MAX_SIZE_MB = int(os.getenv('TEMP_DIR_MAX_SIZE_MB', 5000))  # Máximo 5GB em /tmp/daredevil

# ✅ NOVO: Maximum concurrent transcriptions
MAX_CONCURRENT_TRANSCRIPTIONS = int(os.getenv('MAX_CONCURRENT_TRANSCRIPTIONS', 4))

# Create temp directory if it doesn't exist
Path(TEMP_AUDIO_DIR).mkdir(parents=True, exist_ok=True)

# Django Upload Limits - Configurar para permitir uploads grandes
# 500 MB em bytes (500 * 1024 * 1024)
FILE_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024  # 500 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024  # 500 MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Supported audio formats
SUPPORTED_AUDIO_FORMATS = [
    'opus', 'ogg', 'm4a', 'aac',  # WhatsApp/Instagram
    'mp4', 'mp3', 'wav', 'flac', 'webm'  # Standard formats
]

# Supported video formats (áudio será extraído automaticamente)
SUPPORTED_VIDEO_FORMATS = [
    'mp4', 'avi', 'mov', 'mkv', 'flv', 'wmv', 'webm', 'ogv',
    'ts', 'mts', 'm2ts', '3gp', 'f4v', 'asf'
]

# All supported formats (áudio + vídeo)
ALL_SUPPORTED_FORMATS = SUPPORTED_AUDIO_FORMATS + SUPPORTED_VIDEO_FORMATS

# Português Brasileiro - configurações de processamento de texto
PORTUGUESE_BR_CONFIG = {
    'language_code': 'pt',
    'language_name': 'português',
    'country': 'Brasil',
    'locale': 'pt_BR',
    'encoding': 'utf-8',
    # Hesitações comuns em português a remover
    'hesitations': [
        'hã', 'hm', 'hmm', 'ah', 'é', 'tipo', 'sabe', 'entendeu',
        'né', 'tá', 'ahn', 'mm', 'huh', 'hun', 'shh'
    ],
    # Palavras a capitalizar no início de frases
    'capitalize_after': ['.', '!', '?', '\n'],
    # Abreviações comuns em português
    'abbreviations': {
        'sr': 'Sr.',
        'sra': 'Sra.',
        'dr': 'Dr.',
        'dra': 'Dra.',
        'prof': 'Prof.',
        'profa': 'Profa.',
        'obs': 'Obs.',
        'tel': 'Tel.',
        'cia': 'Cia.',
        'ltda': 'Ltda.',
        'inc': 'Inc.'
    }
}
